INSERT INTO `place` (`id`, `name`, `name_eng`) VALUES 
(NULL, 'Ираклион аэропорт', 'Heraklion Airport'),
(NULL, 'Ираклион Порт', 'Heraklion Port'),
(NULL, 'Ираклион', 'Heraklion Downtown'),
(NULL, 'Амудара', 'Amoudara'),
(NULL, 'Лигарья', 'Ligaria'),
(NULL, 'Агия Пелагия', 'Agia Pelagia'),
(NULL, 'Фоделе', 'Fodele'),
(NULL, 'Коккини Хани', 'Kokkini Hani'),
(NULL, 'Гурнес', 'Gournes'),
(NULL, 'Гувес', 'Gouves'),
(NULL, 'Аналипси', 'Analipsi'),
(NULL, 'Аниссарас', 'Anissaras'),
(NULL, 'Херсониссос', 'Chersonissos'),
(NULL, 'Кутулуфари', 'Koutouloufari'),
(NULL, 'Пископьяно', 'Piskopiano'),
(NULL, 'Сталис', 'Stalis'),
(NULL, 'Малия', 'Malia'),
(NULL, 'Сисси', 'Sissi'),
(NULL, 'Милатос', 'Milatos'),
(NULL, 'Агиос Николаос', 'Agios Nikolaos'),
(NULL, 'Элунда', 'Elounda'),
(NULL, 'Иерапетра', 'Ierapetra'),
(NULL, 'Ретимно', 'Rethimno'),
(NULL, 'Скалета', 'Skaleta'),
(NULL, 'Панормо', 'Pаnormo'),
(NULL, 'Георгиуполис', 'Georgioupolis'),
(NULL, 'Бали', 'Bali'),
(NULL, 'Ханья', 'Chania')
