INSERT INTO `cars` (`id`, `name`, `img`, `places`, `doors`, `kpp`, `fuelType`, `consumption`, `description`, `description_eng`, `summerPrice`, `BodyType`, `ac`, `abs`, `airBags`, `class`, `minAge`, `winterPrice`, `enginePower`) VALUES
(null, 'VW Up', '../../assets/images/VWup.jpg', 4, 3, 'MT', 'Petrol', 5, 'Автомобиль с МКПП. Рабочий объем двигателя 1.0 литр. Кондционер, радио-CD, расход топлива 5л/100 км. В машину свободно входят четверо взрослых пассажира, 1 большая и 1 маленькая дорожные сумки', 'Eng description of the car.', 35, 'Hatchback', b'1', b'1', b'1', 'Economy', 23, 35, NULL),
(null, 'Toyota Yaris', '../../assets/images/toyota_yaris.jpg', 5, 5, 'AT', 'Petrol', 5, 'Автомобиль с вариатором, 1,3 литра, 99 лошадиных сил. Кондционер, радио-CD, расход топлива 5.3 литров/100 км. В машину свободно входят четыре взрослых пассажира, 2 большие дорожные сумки.', 'Eng description of the car.', 40, 'Hatchback', b'0', b'1', b'1', 'Economy', 23, 31, NULL),
(null, 'VW Golf', '../../assets/images/golf.jpg', 5, 5, 'MT', 'Petrol', 8, 'Автомобиль с МКПП, 1.4 литра, 160 лошадинных сил. Климат контроль, радио-CD, расход топлива 8 литров/100 км. В машину свободно входят пять взрослых пассажиров, 2 большие и 2 маленькие дорожные сумки.', 'Eng description of the car.', 50, 'Hatchback', b'1', b'1', b'1', 'Full-Sized', 23, 37, NULL),
(null, 'VW Golf', '../../assets/images/Golf_AMT.jpg', 5, 5, 'AT', 'Petrol', 7, 'Автомобиль с АКПП, 1,4 литра, 120 лошадиных сил. Климат-контроль, радио-CD, расход топлива 6 литров/100 км. В машину свободно входят пять взрослых пассажиров, 2 большие и 2 маленькие дорожные сумки.', 'Eng description of the car.', 65, 'Hatchback', b'0', b'1', b'1', 'Full-Sized', 23, 60, NULL),
(null, 'Nissan Micra', '../../assets/images/Micra.jpg', 5, 5, 'AT', 'Deisel', 9, 'Автомобиль с АКПП, 1,5 литра, 110 лошадиных сил. Кондционер, радио-CD, расход топлива 9 литров/100 км. В машину свободно входят пять взрослых пассажиров, 2 большие и 2 маленькие дорожные сумки.', 'Eng description of the car.', 35, 'Crossover', b'1', b'1', b'1', 'Full-Sized', 23, 28, NULL),
(null, 'VW CADDY 7 PAX', '../../assets/images/Caddy.jpg', 7, 5, 'MT', 'Petrol', 7, 'Семиместный минивен, 1,4 литра, дизель. Специальные условия на длительную аренду.', 'Eng description of the car.', 60, 0, 'Minivan', b'1', b'0', b'1', '0/1/6/3/4', 'Full-Sized', 23, 55, NULL),
(null, 'Hyundai i10', '../../assets/images/Hi10.jpg', 5, 5, 'MT', 'Petrol', 5, 'Автомобиль с МКПП, кондционером, радио-CD, расход топлива 5 литров/100 км. В машину свободно входят четыре взрослых пассажира, 2 большие дорожные сумки.', 'Eng description of the car.', 35, 'Hatchback', b'0', b'1', b'1', 'Economy', 23, 28, NULL),
(null, 'Chevrolet Matiz', '../../assets/images/Matiz.jpg', 4, 5, 'MT', 'Petrol', 4, 'русское описание', 'Eng description of the car', 30, 'Hatchback', b'1', b'1', b'1', 'Economy', 23, 25, NULL),
(null, 'Chevrolet Spark', '../../assets/images/Spark.jpg', 5, 5, 'MT', 'Petrol', 4, 'русское описание', 'Eng description of the car.', 35, 'Hatchback', b'1', b'1', b'1', 'Economy', 23, 28, NULL),
(null, 'VW Polo', '../../assets/images/PoloMan.jpg', 5, 5, 'MT', 'Petrol', 8, 'русское описание', 'Eng description of the car.', 40, 'Hatchback', b'1', b'1', b'1', 'Full-Sized', 23, 31, NULL),
(null, 'Hyunday i20', '../../assets/images/Hi20.jpg', 5, 5, 'MT', 'Petrol', 5, 'русское описание', 'Eng description of the car.', 40, 'Hatchback', b'1', b'1', b'1', 'Economy', 23, 31, NULL),
(null, 'VW Polo Diesel', '../../assets/images/PoloDiesel.jpg', 5, 5, 'MT', 'Deisel', 7, 'русское описание', 'Eng description of the car.', 40, 'Hatchback', b'1', b'1', b'1', 'Full-Sized', 23, 34, NULL),
(null, 'VW Polo', '../../assets/images/PoloAT.jpg', 5, 5, 'AT', 'Petrol', 8, 'русское описание', 'Eng description of the car.', 45, 'Hatchback', b'1', b'1', b'1', 'Full-Sized', 23, 40, NULL);